remote_theme: rampatra/photography
baseurl: "https://www.worksbyshelbirose.com/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Works by Shelbi Rose"
subtitle: "See the world through my eyes!"
author: "Shelbi Rose"
header:
 title: "Works"
 subtitle: "by Shelbi Rose"
footer:
 name: "Hey there, my name is Shelbi"
 bio: "insert bio here"
#social_urls:
 # facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
 # instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
 # github: "https://www.github.com/rampatra"
© 2021 GitHub, Inc.
